---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "image.openshift.io/v1"
  kind: "ImageStream"
  metadata:
    name: "kafka-fuse"
  spec:
    lookupPolicy:
      local: true
    tags:
    - from:
        kind: "ImageStreamImage"
        name: "kafka-fuse@sha256:84febf0d281c6f20ad0cbe46832f42c7e6af0c49e094ed79d5a8ac1ee1b798b2"
        namespace: "fuse-app"
      name: "latest"
