---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  annotations:
    fabric8.io/git-commit: "3b7b2e6799eb572004cd73ea4d59cf8c18710e5f"
    fabric8.io/git-branch: "main"
    fabric8.io/git-url: "git@github.com:wohshon/camel-kafka-mysql.git"
  labels:
    app: "kafka-fuse"
    provider: "fabric8"
    version: "1.0-SNAPSHOT"
    group: "com.redhat"
  name: "kafka-fuse"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: "kafka-fuse"
      provider: "fabric8"
      group: "com.redhat"
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: "3b7b2e6799eb572004cd73ea4d59cf8c18710e5f"
        fabric8.io/git-branch: "main"
        fabric8.io/git-url: "git@github.com:wohshon/camel-kafka-mysql.git"
      labels:
        rht.prod_ver: "7.8"
        rht.comp_ver: "1.0-SNAPSHOT"
        rht.prod_name: "Red_Hat_Integration"
        rht.comp: "kafka-fuse"
        com.company: "Red_Hat"
        app: "kafka-fuse"
        provider: "fabric8"
        version: "1.0-SNAPSHOT"
        group: "com.redhat"
    spec:
      containers:
      - env:
        - name: "SPRING_APPLICATION_JSON"
          value: "{\"server\":{\"undertow\":{\"io-threads\":1, \"worker-threads\"\
            :2 }}}"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "kafka-fuse:latest"
        imagePullPolicy: "IfNotPresent"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: "/actuator/health"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 180
          successThreshold: 1
        name: "spring-boot"
        ports:
        - containerPort: 8080
          name: "http"
          protocol: "TCP"
        - containerPort: 9779
          name: "prometheus"
          protocol: "TCP"
        - containerPort: 8778
          name: "jolokia"
          protocol: "TCP"
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: "/actuator/health"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 10
          successThreshold: 1
        resources:
          limits:
            cpu: "1.0"
            memory: "256Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        securityContext:
          privileged: false
