---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
    discovery.3scale.net/discovery-version: "v1"
    discovery.3scale.net/scheme: "http"
    discovery.3scale.net/port: "8080"
  labels:
    expose: "true"
    discovery.3scale.net/discoverable: "true"
    app: "kafka-fuse"
    provider: "fabric8"
    version: "1.0-SNAPSHOT"
    group: "com.redhat"
  name: "kafka-fuse"
spec:
  ports:
  - name: "http"
    port: 8080
    protocol: "TCP"
    targetPort: 8080
  selector:
    app: "kafka-fuse"
    provider: "fabric8"
    group: "com.redhat"
